export enum Perfil {
  ADMINISTRADOR_SISTEMA = "ADMINISTRADOR_SISTEMA",
  GERENTE_SUPERVISOR = "GERENTE_SUPERVISOR",
  OPERADOR_ESTOQUE = "OPERADOR_ESTOQUE",
  FINANCEIRO_CONTADOR = "FINANCEIRO_CONTADOR",
  APENAS_VISUALIZACAO = "APENAS_VISUALIZACAO",
}
